DENSE:
  T: 1.0
  act: 0
  adv: 0
  bn: 0
  g_steps: 256
  lr_g: 0.001
  model_heterogeneous: true
  nz: 256
  oh: 0
  pretrain_epoch: 300
  sample_batch_size: 256
  save_dir: ./contrib/synthesis
  synthesis_batch_size: 256
FedDistill:
  gamma: 1.0
  global_logit_type: 0
FedGH:
  server_optimizer:
    lr: 0.001
    momentum: 0.9
    type: Adam
    weight_decay: 0.0
FedPPN:
  LP_alpha: 0.9
  LP_layer: 2
  proto_agg_type: train_loss
  temp_idx: 1
  temperature: 10
  use_knn: false
FedPPN_Plus:
  PPN_mode: PPN
  adaptive_weight_lr: 0.001
  epoch_for_learn_weight: 1
  learning_for_adaptability: false
  show_learned_weight_curve: false
  use_knn_graph: false
MHFL:
  add_label_index: false
  all_local: false
  emb_file_path: model_heterogeneity/embedding
  global_model:
    LP_alpha: 0.9
    dropout: 0.5
    feature_dim: 64
    filter_channels:
    - 64
    - 64
    - 64
    hidden: 256
    input_shape:
    - 2708
    - 1433
    layer: 2
    num_classes: 7
    out_channels: 10
    return_proto: false
    task: CV_low
    type: CNN_3layers
    use_bn: true
    warpFC: false
  model_weight_dir: ./contrib/model_weight
  pre_training:
    private_batch_size: 256
    private_epochs: 1
    public_batch_size: 256
    public_epochs: 1
    rePretrain: true
    save_model: true
  public_dataset: mnist
  public_len: 5000
  public_train:
    optimizer:
      lr: 0.001
      type: Adam
      weight_decay: 0.0
  task: node
  tau: 1.0
aggregator:
  BFT_args: {}
  byzantine_node_num: 0
  inside_weight: 1.0
  num_agg_groups: 1
  num_agg_topk: []
  outside_weight: 0.0
  robust_rule: fedavg
asyn:
  use: false
attack:
  alpha_TV: 0.001
  alpha_prop_loss: 0
  attack_method: ''
  attacker_id: -1
  classifier_PIA: randomforest
  edge_num: 100
  edge_path: edge_data/
  freq: 10
  info_diff_type: l2
  inject_round: 0
  insert_round: 100000
  label_type: dirty
  max_ite: 400
  mean:
  - 0.9637
  mia_is_simulate_in: false
  mia_simulate_in_round: 20
  pgd_eps: 2
  pgd_lr: 0.1
  pgd_poisoning: false
  poison_ratio: 0.5
  reconstruct_lr: 0.01
  reconstruct_optim: Adam
  scale_para: 1.0
  scale_poisoning: false
  self_epoch: 6
  self_lr: 0.05
  self_opt: false
  setting: fix
  std:
  - 0.1592
  target_label_ind: -1
  trigger_path: trigger/
  trigger_type: edge
backend: torch
cfg_file: ''
change_hidden_when_warpFC: false
check_completeness: false
criterion:
  type: CrossEntropyLoss
data:
  args: []
  batch_size: 64
  cSBM_phi:
  - 0.5
  - 0.5
  - 0.5
  cache_dir: ''
  consistent_label_distribution: true
  drop_last: false
  file_path: ''
  hetero_data_name: []
  hetero_synth_batch_size: 32
  hetero_synth_feat_dim: 128
  hetero_synth_prim_weight: 0.5
  is_debug: false
  loader: ''
  local_eval_whole_test_dataset: true
  max_query_len: 128
  max_seq_len: 384
  max_tgt_len: 128
  num_contrast: 0
  num_of_client_for_data: []
  num_steps: 30
  num_workers: 0
  pre_transform: []
  quadratic:
    dim: 1
    max_curv: 12.5
    min_curv: 0.02
  root: data/
  save_data: false
  server_holds_all: false
  shuffle: true
  sizes:
  - 10
  - 5
  splits:
  - 0.8
  - 0.1
  - 0.1
  splitter: louvain
  splitter_args: []
  subsample: 1.0
  target_transform: []
  test_pre_transform: []
  test_target_transform: []
  test_transform: []
  transform: []
  trunc_stride: 128
  type: cora
  val_pre_transform: []
  val_target_transform: []
  val_transform: []
  walk_length: 2
dataloader:
  batch_size: 1
  drop_last: false
  num_steps: 30
  num_workers: 0
  pin_memory: false
  shuffle: true
  sizes:
  - 10
  - 5
  theta: -1
  type: pyg
  walk_length: 2
device: 0
distribute:
  use: false
early_stop:
  delta: 0.0
  improve_indicator_mode: best
  patience: 50
eval:
  best_res_update_round_wise_key: val_acc
  count_flops: true
  freq: 1
  metrics:
  - acc
  - global_model_acc
  - ensemble_model_acc
  monitoring: []
  report:
  - weighted_avg
  - avg
  split:
  - test
  - val
exp_name: FedAvg_on_cfg.data.type_1709122246.1045618
expname: fedppn_gcn_on_cora_lr0.25_lstep4
expname_tag: ''
fccl:
  beta: 0.1
  loss_dual_weight: 1
  off_diag_weight: 0.0051
  pub_aug: weak
  structure: homogeneity
feat_engr:
  num_bins: 5
  scenario: hfl
  secure:
    dp: {}
    encrypt:
      type: dummy
    key_size: 3072
    type: encrypt
  selec_threshold: 0.05
  selec_woe_binning: quantile
  type: ''
fedapen:
  adaptability_ratio: 0.05
  epoch_for_learn_weight: 1
federate:
  atc_load_from: ''
  atc_vanilla: false
  client_num: 5
  data_weighted_aggr: false
  ignore_weight: false
  join_in_info: []
  make_global_eval: false
  master_addr: 127.0.0.1
  master_port: 29500
  merge_test_data: false
  merge_val_data: false
  method: fedppn
  mode: standalone
  online_aggr: false
  process_num: 1
  resource_info_file: ''
  restore_from: ''
  sample_client_num: 5
  sample_client_rate: 1.0
  sampler: uniform
  save_to: ''
  share_local_model: false
  total_round_num: 200
  unseen_clients_rate: 0.0
  use_diff: false
  use_ss: false
fedgraphkd: {}
fedhenn:
  eta: 0.001
fedkd:
  tmax: 0.98
  tmin: 0.95
  use_SVD: true
fedmd:
  digest_epochs: 1
  pre_training:
    private_batch_size: 256
    private_epochs: 1
    public_batch_size: 256
    public_epochs: 1
    rePretrain: true
  public_subset_size: 5000
  revisit_epochs: 1
fedopt:
  use: false
fedpcl:
  debug: false
  show_verbose: false
fedproto:
  iid: false
  only_CE_loss: false
  proto_weight: 1.0
  shots: 100
  show_verbose: false
  stdev: 2
  test_shots: 15
  train_shots_max: 110
  unequal: false
  use_similarity_for_inference: false
  ways: 5
fedprox:
  use: false
fedsageplus:
  a: 1.0
  b: 1.0
  c: 1.0
  fedgen_epoch: 200
  gen_hidden: 128
  hide_portion: 0.5
  loc_epoch: 1
  num_pred: 5
fedswa:
  use: false
finetune:
  batch_or_epoch: epoch
  before_eval: false
  epoch_linear: 10
  freeze_param: ''
  local_param: []
  local_update_steps: 1
  lr_linear: 0.005
  optimizer:
    lr: 0.1
    type: SGD
  scheduler:
    type: ''
    warmup_ratio: 0.0
  simple_tuning: false
  weight_decay: 0.0
flitplus:
  factor_ema: 0.8
  lambdavat: 0.5
  tmpFed: 0.5
  weightReg: 1.0
fml:
  alpha: 0.5
  beta: 0.5
  meme_model:
    T: 5
    dropout: 0.5
    hidden: 256
    in_channels: 0
    layer: 2
    out_channels: 1
    task: CV_low
    type: CNN
    warpFC: false
fpl:
  share_model_weight: false
  temperature: 0.02
fsfl:
  DI_optimizer:
    lr: 0.001
    type: Adam
    weight_decay: 0.0001
  DI_optimizer_step_2:
    lr: 0.0001
    type: Adam
    weight_decay: 0.0001
  MAFL_batch_size: 256
  N_samples_per_class: 12
  collaborative_epoch: 1
  collaborative_num_samples_epochs: 5000
  domain_identifier_batch_size: 30
  domain_identifier_epochs: 4
  gan_local_epochs: 4
  private_classes:
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  public_classes:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
gcflplus:
  EPS_1: 0.05
  EPS_2: 0.1
  seq_length: 5
  standardize: false
grad:
  grad_accum_count: 1
  grad_clip: 5.0
hpo:
  fedex:
    cutoff: 0.0
    diff: false
    eta0: -1.0
    flatten_ss: true
    gamma: 0.0
    pi_lr: 0.01
    psn: false
    sched: auto
    ss: ''
    use: false
  fts:
    M: 100
    M_target: 200
    allow_load_existing_info: true
    diff: false
    fed_bo_max_iter: 50
    g_var: 1.0e-06
    gp_opt_schedule: 1
    local_bo_epochs: 50
    local_bo_max_iter: 50
    ls: 1.0
    obs_noise: 1.0e-06
    ss: ''
    target_clients: []
    use: false
    v_kernel: 1.0
    var: 0.1
  init_cand_num: 16
  larger_better: false
  metric: client_summarized_weighted_avg.val_loss
  num_workers: 0
  pbt:
    max_stage: 5
    perf_threshold: 0.1
  pfedhpo:
    discrete: false
    ss: ''
    target_fl_total_round: 1000
    train_anchor: false
    train_fl: false
    use: false
  scheduler: rs
  sha:
    budgets: []
    elim_rate: 3
    iter: 0
  ss: ''
  table:
    eps: 0.1
    idx: 0
    num: 27
  trial_index: 0
  working_folder: hpo
model:
  LP_alpha: 0.9
  T: 5
  contrast_temp: 1.0
  contrast_topk: 100
  downstream_tasks: []
  dropout: 0.5
  embed_size: 8
  feature_dim: 64
  fedpcl:
    input_size: 512
    model_weight_dir: ./contrib/model_weight
    output_dim: 256
  fedproto_femnist_channel_temp: 18
  filter_channels:
  - 64
  - 64
  - 64
  fsfl_cnn_layer1_out_channels: 128
  fsfl_cnn_layer2_out_channels: 512
  gamma: 0
  graph_pooling: mean
  hidden: 64
  in_channels: 0
  input_shape: []
  label_smoothing: 0.1
  lambda_: 0.1
  layer: 10
  length_penalty: 2.0
  max_answer_len: 30
  max_length: 200
  max_tree_depth: 3
  min_length: 1
  model_num_per_trainer: 1
  model_type: google/bert_uncased_L-2_H-128_A-2
  n_best_size: 20
  no_repeat_ngram_size: 3
  null_score_diff_threshold: 0.0
  num_beams: 5
  num_classes: 7
  num_item: 0
  num_labels: 1
  num_of_trees: 10
  num_user: 0
  out_channels: 64
  pretrain_resnet: false
  pretrain_tasks: []
  return_proto: true
  stage: ''
  stride:
  - 1
  - 4
  task: node
  type: gpr
  use_bias: true
  use_bn: true
  use_contrastive_loss: false
  warpFC: true
nbafl:
  use: false
outdir: exp\fedppn_gcn_on_cora_lr0.25_lstep4\sub_exp_20240228201048
personalization:
  K: 5
  beta: 1.0
  epoch_feature: 1
  epoch_linear: 2
  local_param: []
  local_update_steps: 4
  lr: 0.25
  lr_feature: 0.1
  lr_linear: 0.1
  regular_weight: 0.1
  share_non_trainable_para: false
  weight_decay: 0.0
plot_acc_curve: false
poi:
  LP_alpha: 0.5
  LP_layer: 1
  proto_agg_type: train_loss
  tau1: 10
  temp_idx: 1
  use_knn: false
print_decimal_digits: 6
quantization:
  method: none
  nbits: 8
regularizer:
  mu: 0.0
  type: ''
result_floder: model_heterogeneity/result/manual
save_history_result_avg: true
save_history_result_per_client: true
seed: 0
sgdmf:
  use: false
show_client_best_individual: true
show_detailed_communication_info: false
show_label_distribution: false
train:
  batch_or_epoch: epoch
  local_update_steps: 4
  optimizer:
    lr: 0.25
    momentum: 0.9
    type: SGD
    weight_decay: 0.0005
  scheduler:
    type: ''
    warmup_ratio: 0.0
trainer:
  disp_freq: 50
  local_entropy:
    alpha: 0.75
    eps: 0.0001
    gamma: 0.03
    inc_factor: 1.0
  sam:
    adaptive: false
    eta: 0.0
    rho: 1.0
  type: fedppn_trainer
  val_freq: 100000000
use_gpu: true
verbose: 1
vertical:
  use: false
vis_embedding: false
wandb:
  use: false

